### ISSUE TITLE
Share Strengths and Weaknesses

### ISSUE THREAD

**Issue by ClaudiaLapalme** [ClaudiaLapalme/SOEN-343#1]

**Comment by ClaudiaLapalme** [comment]
Strengths:
* Organization
* Willingness to learn on the fly
* Back-end

Weaknesses:
* Front-end
* Bad at reading instructions properly

**Comment by gisellemartel** [comment]
Strengths:

- Front-end
- back-end

Weaknesses:

- Databases
- Lack of knowledge in Java frameworks
